repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: [--profile, black, --line-length=79]

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      exclude: (migrations|config/settings/)
      additional_dependencies:
        - flake8-docstrings

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
    - id: black
      args: [--line-length=79]

- repo: local
  hooks:
    - id: export-dev-requirements
      name: Export DEV requirements
      language: system
      pass_filenames: false
      entry: poetry export --without-hashes --with dev --output requirements/develop.txt
      files: ^(pyproject.toml|poetry.lock)$
    - id: export-prod-requirements
      name: Export PROD requirements
      language: system
      pass_filenames: false
      entry: poetry export --without-hashes --output requirements/production.txt
      files: ^(pyproject.toml|poetry.lock)$
